# Site settings
author: Joseph Choi
title: 
header-img: img/home-bg.png
email: jdc07@live.com
copyright_name: Joseph Choi
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jaydeecee-cloud

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
